name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - run: go mod tidy

      - name: build-linux
        run: |
          CGO_ENABLED=0 GOARCH=amd64 go build -ldflags "-w -s" -o ./dist/xray ./

      - name: build-windows
        run: |
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-w -s" -o ./dist/xray.exe ./

      - name: compress
        run: |
          tar -czf Xray-linux-64.tar.gz    ./dist/xray
          zip -r   Xray-linux-64.zip       ./dist/xray.exe
          tar -czf Xray-windows-64.tar.gz  ./dist/xray
          zip -r   Xray-windows-64.zip     ./dist/xray.exe

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Version ${{ github.ref_name }} ðŸš€"
          draft: false
          prerelease: false
          generate_release_notes: true
          body_path: changelog.md
          files: |
            Xray-linux-64.tar.gz
            Xray-linux-64.zip
            Xray-windows-64.tar.gz
            Xray-windows-64.zip
